cluster:
    mkdir -p logs/{rule} &&
    sbatch
        --qos=batch
        --cpus-per-task={threads}
        --mem={resources.mem}
        --job-name=RFP_snakemake_{rule}
        --output=logs/{rule}/RFP_snakemake_{rule}.%j.out
        --error=logs/{rule}/RFP_snakemake_{rule}.%j.err
        --time={resources.time}
        --nodes=1
        --ntasks=1
default-resources: [mem=5000, time=60]
